tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew act
brew aws-iam-authenticator
brew awscli
brew bat
brew brew-cask-completion
brew coreutils
brew curl
brew direnv
brew dockutil
brew exa
brew fluxcd/tap/flux
brew fzf
brew gawk
brew gh
brew git-chglog/git-chglog/git-chglog
brew gnu-sed
brew gnu-tar
brew gnupg
brew go
brew grpcurl
brew jpeg
brew jq
brew yq
brew kubecfg
brew kubectx
brew kustomize
brew less
brew libgit2
brew moreutils
brew nghttp2
brew node
brew openssh
brew pinentry-mac
brew pre-commit
brew sops
brew terraform
brew terraform-docs
brew terragrunt
brew tflint
brew tfsec
brew tmux
brew tree
brew vegeta
brew watch
brew wget
brew ykman
brew zsh
cask authy
cask docker
cask font-consolas-for-powerline
cask font-fira-code
cask font-roboto-mono
cask font-roboto-mono-for-powerline
cask font-meslo-lgs-nerdfont-bold
cask font-meslo-lgs-nerdfont-bold-italic
cask font-meslo-lgs-nerdfont-italic
cask font-meslo-lgs-nerdfont-regular
cask google-chrome
cask visual-studio-code
cask iterm2
