unset PATH
export PATH="$PATH:$(brew --prefix openssh)/bin"
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$PATH:/Applications/OrbStack.app/Contents/MacOS/xbin"
# export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS/"
# export PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin"
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
# export LDFLAGS="-L/opt/homebrew/opt/node@20/lib"
# export CPPFLAGS="-I/opt/homebrew/opt/node@20/include"