#!/usr/bin/env bash


set -e
set -o errexit
set -o pipefail

ROLEARN=$1

test -n "$ROLEARN" || (echo missing ROLEARN; exit 1)

set +e
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
SESSION=$(aws sts assume-role --role-arn $ROLEARN --role-session-name assumed-by-$USER)
env -u AWS_SECURITY_TOKEN >/dev/null 2>&1
export AWS_ACCESS_KEY_ID=$(echo $SESSION | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo $SESSION | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo $SESSION | jq -r .Credentials.SessionToken)

test -n "$AWS_SECRET_ACCESS_KEY" || (echo missing AWS_SECRET_ACCESS_KEY; exit 1)
aws sts get-caller-identity
