#!/usr/bin/env bash

local user rdshost token

user="$1"
rdshost="${2:-$(aws rds describe-db-cluster-endpoints --output text --query 'DBClusterEndpoints[?EndpointType==`WRITER`].Endpoint')}"
echo "Using host $rdshost"  >&2

token="$(aws rds generate-db-auth-token --hostname $rdshost --port 3306 --username $user)"

if [[ ! "$token" =~ "X-Amz-Security-Token=" ]]; then
  echo "No Token Found. Check credentials/profile" >&2
  exit 1
fi
echo "$token"