#!/usr/bin/env bash

USER="$1"
RDSHOST="${2:-$(aws rds describe-db-cluster-endpoints --output text --query 'DBClusterEndpoints[?EndpointType==`WRITER`].Endpoint')}"
echo "Using host $RDSHOST"  >&2

TOKEN="$(aws rds generate-db-auth-token --hostname $RDSHOST --port 3306 --username $USER)"

if [[ ! "$TOKEN" =~ "X-Amz-Security-Token=" ]]; then
  echo "No Token Found. Check credentials/profile" >&2
  exit 1
fi

docker run -it --rm thetote/mysql-iam-client:latest --host="$RDSHOST" --port=3306 --user=$USER --password="$TOKEN"