
{{- $refreshPeriod := "168h" }}

[_chezmoi]
    type = "file"
    url = 'https://raw.githubusercontent.com/twpayne/chezmoi/master/completions/chezmoi.zsh'
    refreshPeriod = "{{ $refreshPeriod }}"
[_fd]
    type = "file"
    url = 'https://raw.githubusercontent.com/sharkdp/fd/master/contrib/completion/_fd'
    refreshPeriod = "{{ $refreshPeriod }}"
[_docker]
    type = "file"
    url = 'https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker'
    refreshPeriod = "{{ $refreshPeriod }}"
[_kubectx]
    type = "file"
    url = 'https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/_kubectx.zsh'
    refreshPeriod = "{{ $refreshPeriod }}"
[_kubens]
    type = "file"
    url = 'https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/_kubens.zsh'
    refreshPeriod = "{{ $refreshPeriod }}"
[_terragrunt]
    type = "file"
    url = 'https://raw.githubusercontent.com/thuandt/zsh-terraform/master/_terragrunt'
    refreshPeriod = "{{ $refreshPeriod }}"
