POWERLEVEL9K_MODE="nerdfont-complete"

# Standard Settings
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=($'%F{red} \uf7c6 %f %F{yellow}❯ ')

# Prompt Segments
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status aws kubecontext)

# Colors
POWERLEVEL9K_HISTORY_BACKGROUND='green'
P9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND=$P9KGT_YELLOW
P9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND=$P9KGT_RED
POWERLEVEL9K_KUBECONTEXT_BACKGROUND='004'
POWERLEVEL9K_KUBECONTEXT_FOREGROUND='000'
